#!/usr/bin/env python3
"""Fold results/ and the plan documents into where-we-are: built, now, next.

Every other artifact specbuild produces is written for an executor -- the
constitution and packets for building agents, plan.lock.yaml for the validator,
map.md for the environment. None is written for someone trying to understand the
project. This is that one, and it is computed rather than maintained.

`results/` is an append-only log of what agents actually reported. Unit status,
gate status and the provenance pins are a *fold* over it, not state anyone
keeps: there is no progress file to write, to hand-edit, or to go stale. Ask
the question and the answer is recomputed from evidence.

Extraction only, no judgement -- the same standard validate_plan.py holds
itself to. In particular the verified/claimed split is mechanical: a unit is
built when its result carries real verification output, never because it says
so. Narration on top of these facts is the Explain stage's job, and no claim in
it may exceed what this script found.

Usage:
    python3 explain.py <plan-dir> [--spec <spec.md>] [--json] [--write]

    <plan-dir>  directory holding build-plan.md (e.g. spec/plan)
    --spec      spec file, for the header only
    --json      structured output on stdout, for automation. Nothing is written
    --write     also write <plan-dir>/briefing.md as a point-in-time snapshot,
                for handing the project to someone who will not run this

Exit 0 = reported, 1 = nothing to report on (no plan).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
try:
    from validate_plan import parse_units, depth_of, section_text, is_none
except ImportError:  # pragma: no cover - only when copied without its sibling
    print("ERROR explain.py needs validate_plan.py beside it -- both are copied "
          "into the plan directory together. Parsing the plan twice with two "
          "sets of regexes is how the two drift.", file=sys.stderr)
    raise SystemExit(1)

VERSION = "1.0.0"

GENERATED_MARKER = (
    "<!-- GENERATED by explain.py -- a point-in-time snapshot, not a maintained "
    "document. Regenerate: python3 explain.py <plan-dir> --write -->")

# Orientation for humans. Agents build from packets, whose contracts are exact;
# a narrative summary standing in for a contract is the divergence failure this
# whole skill is built against.
AUDIENCE_BANNER = (
    "> **Orientation for humans.** Building agents work from their packet and "
    "the unit contract in `build-plan.md`, never from this file.")

RESULT_FIELD_RE = re.compile(r"^\*\*([A-Za-z][A-Za-z ]*?):\*\*\s*(.*?)\s*$", re.M)
UNIT_ID_RE = re.compile(r"U-\d+")

# A result claims completion with these; the claim is only believed when the
# verification section also carries output.
DONE_WORDS = re.compile(r"\b(verified|done|complete|completed|passed|green)\b", re.I)
BLOCKED_WORDS = re.compile(r"\b(blocked|blocker|stopped|halted)\b", re.I)

# Output that is present but says nothing -- an empty fence, a bare "ok". Treated
# as absent, because "I ran it, trust me" is exactly the self-report Stage 6
# refuses to accept.
TRIVIAL_OUTPUT_RE = re.compile(r"^[\s`~]*$|^[\s`~]*(ok|pass(ed)?|success|done|n/?a)[\s`.!~]*$", re.I)

STATE_ORDER = ["blocked", "claimed", "in-progress", "verified", "not-started"]


# --------------------------------------------------------------------------
# Reading the log
# --------------------------------------------------------------------------

def clean_section(body: str) -> str:
    """A section's real content: template comments stripped, and an explicit
    "(none)" normalised to empty.

    Normalising here rather than at each use site is deliberate -- the template
    asks agents to write "(none)", and a reader that forgets to handle it
    reports every well-formed result as a model-drift signal.
    """
    body = re.sub(r"<!--.*?-->", "", body, flags=re.DOTALL)
    lines = [l for l in body.splitlines() if l.strip()]
    if not lines:
        return ""
    if all(is_none(l.strip().lstrip("-* ").strip()) or not l.strip().lstrip("-* ")
           for l in lines):
        return ""
    return "\n".join(lines)


def parse_result(path: Path) -> dict:
    """One results/<unit-id>.md, read defensively.

    Agents write these, so the parse tolerates drift: a malformed file is
    reported as unparseable rather than crashing the report or, worse, being
    silently read as 'nothing happened'.
    """
    out = {"path": path.name, "fields": {}, "verification": "", "blockage": "",
           "missing_context": "", "unreadable": False}
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        out["unreadable"] = True
        return out

    out["fields"] = {k.strip(): v.strip() for k, v in RESULT_FIELD_RE.findall(text)}
    out["verification"] = clean_section(section_text(text, r"verification|output|verified by"))
    out["blockage"] = clean_section(section_text(text, r"blockage|blocked|stop"))
    out["missing_context"] = clean_section(section_text(text, r"missing context"))
    out["text"] = text
    return out


def has_real_output(result: dict) -> bool:
    """Verification output that actually contains something.

    The whole verified/claimed distinction rests here, so it is deliberately
    strict: a heading with an empty fence under it is not evidence.
    """
    body = result.get("verification", "")
    if not body.strip():
        return False
    stripped = "\n".join(l for l in body.splitlines()
                         if not l.strip().startswith("**"))
    return not TRIVIAL_OUTPUT_RE.match(stripped.strip())


def classify(uid: str, result: dict | None, packets_dir: Path) -> str:
    """State of one unit, from evidence rather than assertion.

    verified     result carries real verification output
    claimed      result says done, no output recorded -- the fabrication guard
    blocked      the agent stopped and reported, which is correct behaviour
    in-progress  dispatched, nothing reported back yet
    not-started  no packet, no result
    """
    if result is None:
        if packets_dir.is_dir() and any(packets_dir.glob(f"{uid}*")):
            return "in-progress"
        return "not-started"
    if result["unreadable"]:
        return "in-progress"

    status = result["fields"].get("Status", "")
    if result["blockage"] or BLOCKED_WORDS.search(status):
        return "blocked"
    if has_real_output(result):
        return "verified"
    if DONE_WORDS.search(status) or DONE_WORDS.search(result.get("text", "")[:400]):
        return "claimed"
    return "in-progress"


def read_results(plan_dir: Path) -> tuple[dict[str, dict], list[str], float]:
    """All results, keyed by unit id. Also returns orphans and the newest mtime."""
    results_dir = plan_dir / "results"
    by_unit: dict[str, dict] = {}
    orphans: list[str] = []
    newest = 0.0
    if not results_dir.is_dir():
        return by_unit, orphans, newest
    for f in sorted(results_dir.glob("*.md")):
        newest = max(newest, f.stat().st_mtime)
        m = UNIT_ID_RE.search(f.stem) or UNIT_ID_RE.search(
            f.read_text(encoding="utf-8", errors="replace")[:200])
        if not m:
            orphans.append(f.name)
            continue
        by_unit[m.group(0)] = parse_result(f)
    return by_unit, orphans, newest


# --------------------------------------------------------------------------
# Reading the plan
# --------------------------------------------------------------------------

def wave_key(w: str) -> float:
    try:
        return float(w)
    except ValueError:
        return 1e9


def parse_table(body: str, min_cells: int, skip_first: set[str]) -> list[list[str]]:
    rows = []
    for line in body.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < min_cells or set("".join(cells)) <= set("-: "):
            continue
        if cells[0].lower() in skip_first:
            continue
        rows.append(cells)
    return rows


def parse_ladder(plan_text: str) -> list[dict]:
    """The increment ladder -- what a person can do that they could not before.
    This is what makes Next read as outcomes rather than unit ids."""
    body = section_text(plan_text, r"increment ladder")
    out = []
    for cells in parse_table(body, 4, {"#", "increment"}):
        out.append({"n": cells[0], "increment": cells[1],
                    "type": cells[2].strip("*"), "usable": cells[3],
                    "gate": cells[4] if len(cells) > 4 else ""})
    return out


def parse_amendments(plan_text: str) -> list[str]:
    """Spec amendments still marked proposed -- these are waiting on a human,
    and today nothing surfaces them anywhere."""
    body = section_text(plan_text, r"spec amendments")
    out = []
    for cells in parse_table(body, 4, {"amendment"}):
        if any("proposed" in c.lower() for c in cells):
            out.append(cells[0])
    return out


def current_constitution(plan_dir: Path) -> tuple[str, set[str]]:
    """Current version, and the versions introduced by an amendment.

    A unit is stale only when an *amendment* landed after it was built;
    non-amendments never flag, which is what stops version churn producing
    false alarms.
    """
    path = plan_dir / "constitution.md"
    if not path.exists():
        return "", set()
    text = path.read_text(encoding="utf-8", errors="replace")
    # The template writes `**Version:** C1`, but a hand-assembled constitution
    # commonly titles itself `# Constitution C1`. Accept either rather than
    # silently reporting no version, which would disable the staleness check.
    m = (re.search(r"\*\*Version:\*\*\s*(C\d+)", text)
         or re.search(r"^#\s+.*?\b(C\d+)\b", text, re.M))
    version = m.group(1) if m else ""
    amendments = set()
    for cells in parse_table(section_text(text, r"amendment history"), 3, {"version"}):
        if len(cells) > 2 and cells[2].strip().lower() == "amendment":
            amendments.add(cells[0].strip())
    return version, amendments


def constitution_stale(built_under: str, current: str, amendments: set[str]) -> bool:
    if not built_under or not current or built_under == current:
        return False
    try:
        lo, hi = int(built_under.lstrip("C")), int(current.lstrip("C"))
    except ValueError:
        return False
    return any(lo < int(a.lstrip("C")) <= hi
               for a in amendments if a.lstrip("C").isdigit())


# --------------------------------------------------------------------------
# The fold
# --------------------------------------------------------------------------

def fold(plan_dir: Path, spec: Path | None) -> dict:
    plan_text = (plan_dir / "build-plan.md").read_text(encoding="utf-8",
                                                       errors="replace")
    units = parse_units(plan_text)
    results, orphans, newest = read_results(plan_dir)
    packets_dir = plan_dir / "packets"
    version, amendments = current_constitution(plan_dir)

    rows = []
    for uid in sorted(units, key=lambda u: (wave_key(units[u]["fields"].get("Wave", "?")), u)):
        u = units[uid]
        r = results.get(uid)
        state = classify(uid, r, packets_dir)
        built_under = ""
        if r:
            m = re.search(r"C\d+", r["fields"].get("Constitution", ""))
            built_under = m.group(0) if m else ""
        rows.append({
            "id": uid,
            "name": u["name"],
            "wave": u["fields"].get("Wave", "?"),
            "depth": depth_of(u),
            "state": state,
            "implements": u["fields"].get("Implements", ""),
            "evidence": f"results/{r['path']}" if r else "",
            "constitution": built_under,
            "stale_law": constitution_stale(built_under, version, amendments),
            "missing_context": (r or {}).get("missing_context", "").strip(),
            "blockage": (r or {}).get("blockage", "").strip(),
        })

    by_state = {s: [r for r in rows if r["state"] == s] for s in STATE_ORDER}
    waves: dict[str, list[dict]] = {}
    for r in rows:
        waves.setdefault(r["wave"], []).append(r)

    return {
        "plan_dir": str(plan_dir),
        "spec": str(spec) if spec else "",
        "constitution": version,
        "unit_count": len(rows),
        "units": rows,
        "by_state": by_state,
        "waves": waves,
        "ladder": parse_ladder(plan_text),
        "proposed_amendments": parse_amendments(plan_text),
        "orphan_results": orphans,
        "newest_result_mtime": newest,
        "plan_hash": hashlib.sha256(plan_text.encode("utf-8")).hexdigest()[:16],
    }


def next_stage(f: dict) -> str:
    """Name a specbuild stage, the way specforge's status.py names a mode."""
    s = f["by_state"]
    if s["blocked"]:
        return (f"resolve blockages -- {len(s['blocked'])} unit(s) stopped and "
                f"reported, which is correct behaviour; they need a human")
    if s["claimed"]:
        return (f"**Reconcile** (Stage 6) -- {len(s['claimed'])} unit(s) claim "
                f"completion with no recorded verification output")
    if any(u["stale_law"] for u in f["units"]):
        return "**Reconcile** (Stage 6) -- an amendment landed after some units were built"
    if not any(s[k] for k in ("verified", "in-progress", "claimed", "blocked")):
        return "**Render** (Stage 4) -- the plan exists but nothing has been dispatched"
    if s["in-progress"]:
        return f"in flight -- {len(s['in-progress'])} unit(s) dispatched, nothing reported back yet"
    if s["not-started"]:
        return "**Render** (Stage 4) for the next wave"
    return "the plan is fully verified -- nothing left to build"


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def render(f: dict, stale_note: str = "") -> str:
    L: list[str] = []
    add = L.append
    s = f["by_state"]
    verified, claimed = s["verified"], s["claimed"]

    add(f"# Where we are\n")
    head = [f"**Plan:** `{f['plan_dir']}`"]
    if f["spec"]:
        head.append(f"**Spec:** `{f['spec']}`")
    if f["constitution"]:
        head.append(f"**Constitution:** {f['constitution']}")
    head.append(f"**Units:** {f['unit_count']}")
    add(" · ".join(head))
    if stale_note:
        add(f"\n⚠ {stale_note}")

    # ---- Built ----
    add("\n## Built\n")
    if not verified and not claimed:
        add("Nothing verified yet.")
    if verified:
        add(f"**Verified — {len(verified)} unit(s)**, each with recorded "
            f"verification output:\n")
        for u in verified:
            flag = "  ⚠ built under a superseded law" if u["stale_law"] else ""
            add(f"- **{u['name']}** ({u['id']}, wave {u['wave']}) — evidence: "
                f"`{u['evidence']}`{flag}")
    if claimed:
        add(f"\n**Claimed but unverified — {len(claimed)} unit(s).** Marked done "
            f"with no verification output recorded, so this is a self-report, "
            f"not evidence:\n")
        for u in claimed:
            add(f"- {u['name']} ({u['id']}, wave {u['wave']})"
                + (f" — `{u['evidence']}`" if u["evidence"] else ""))

    # ---- Now ----
    add("\n## Now\n")
    now_lines = []
    if s["blocked"]:
        now_lines.append(f"**Blocked — {len(s['blocked'])} unit(s)** stopped and "
                         f"reported rather than improvising:")
        for u in s["blocked"]:
            first = next((l.strip() for l in u["blockage"].splitlines() if l.strip()), "")
            now_lines.append(f"- {u['name']} ({u['id']}) — {first[:120]}")
    if s["in-progress"]:
        now_lines.append(f"\n**In flight — {len(s['in-progress'])} unit(s)** "
                         f"dispatched, nothing reported back yet:")
        for u in s["in-progress"]:
            now_lines.append(f"- {u['name']} ({u['id']}, wave {u['wave']})")
    if f["proposed_amendments"]:
        now_lines.append(f"\n**Waiting on a decision — {len(f['proposed_amendments'])} "
                         f"proposed spec amendment(s):**")
        for a in f["proposed_amendments"]:
            now_lines.append(f"- {a}")
    drift = [u for u in f["units"] if u["missing_context"]]
    if drift:
        now_lines.append(f"\n**Model drift signal — {len(drift)} unit(s) reported "
                         f"missing context.** Repeated reports mean the "
                         f"interpretation is wrong, not that units were careless:")
        for u in drift:
            first = next((l.strip() for l in u["missing_context"].splitlines()
                          if l.strip()), "")
            now_lines.append(f"- {u['id']} — {first[:120]}")
    if f["orphan_results"]:
        now_lines.append(f"\n**Unmatched results:** {', '.join(f['orphan_results'])} "
                         f"— no unit id found, so these are counted nowhere above.")
    if f["newest_result_mtime"]:
        when = datetime.fromtimestamp(f["newest_result_mtime"]).strftime("%Y-%m-%d")
        now_lines.append(f"\nLast recorded activity: {when}.")
    add("\n".join(now_lines) if now_lines else
        "Nothing in flight, nothing blocked, nothing awaiting a decision.")

    # ---- Next ----
    add("\n## Next\n")
    done_ids = {u["id"] for u in verified}
    remaining = [w for w in sorted(f["waves"], key=wave_key)
                 if any(u["id"] not in done_ids for u in f["waves"][w])]
    if not remaining:
        add("Every wave is verified.")
    else:
        for w in remaining:
            pend = [u for u in f["waves"][w] if u["id"] not in done_ids]
            depths = {u["depth"] for u in pend}
            # Contract depth already encodes confidence. Saying so keeps a
            # `named`-only wave from reading like a plan.
            if depths <= {"named"}:
                conf = " — *named only, so this is a placeholder, not a plan*"
            elif "named" in depths or "sketched" in depths:
                conf = " — *partly sketched; contracts firm up as the wave nears*"
            else:
                conf = ""
            add(f"**Wave {w}** ({len(pend)} unit(s) outstanding){conf}")
            for u in pend:
                add(f"- {u['name']} ({u['id']})")
            add("")
    if f["ladder"]:
        add("**Increment ladder** — what becomes possible:\n")
        for r in f["ladder"]:
            add(f"- **{r['increment']}** ({r['type']}) — {r['usable']}")

    add(f"\n---\n\n→ Recommended next: {next_stage(f)}")
    return "\n".join(L) + "\n"


def to_json(f: dict) -> str:
    out = {k: f[k] for k in ("plan_dir", "spec", "constitution", "unit_count",
                             "proposed_amendments", "orphan_results", "plan_hash")}
    out["counts"] = {s: len(f["by_state"][s]) for s in STATE_ORDER}
    out["units"] = [{k: u[k] for k in ("id", "name", "wave", "depth", "state",
                                       "evidence", "constitution", "stale_law")}
                    for u in f["units"]]
    out["next"] = re.sub(r"\*\*", "", next_stage(f))
    return json.dumps(out, indent=2)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan_dir", type=Path)
    ap.add_argument("--spec", type=Path, default=None)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--write", action="store_true",
                    help="also write <plan-dir>/briefing.md as a snapshot")
    args = ap.parse_args()

    plan_dir = args.plan_dir
    if not (plan_dir / "build-plan.md").exists():
        print(f"ERROR no build-plan.md in {plan_dir} -- there is no build to explain "
              f"yet.\n      If the spec is still being written, ask specforge for "
              f"status instead.", file=sys.stderr)
        return 1

    f = fold(plan_dir, args.spec)

    briefing = plan_dir / "briefing.md"
    stale_note = ""
    if briefing.exists():
        b = briefing.stat().st_mtime
        if f["newest_result_mtime"] > b or (plan_dir / "build-plan.md").stat().st_mtime > b:
            stale_note = ("`briefing.md` predates the current plan or results — "
                          "regenerate it with --write before sharing it.")

    if args.json:
        print(to_json(f))
        return 0

    body = render(f, stale_note)
    print(body)

    if args.write:
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        briefing.write_text(
            f"{GENERATED_MARKER}\n\n{AUDIENCE_BANNER}\n\n"
            f"*Snapshot taken {stamp} · plan `{f['plan_hash']}` · "
            f"explain.py {VERSION}*\n\n" + body, encoding="utf-8")
        print(f"\nwrote {briefing}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
