#!/usr/bin/env bash
# Sync ROADMAP.md (repo root, for GitHub) → docs/roadmap.md (for mkdocs site).
#
# The roadmap doesn't change often. When it does, edit /ROADMAP.md and run
# this script to update the mkdocs version. CI runs this as a check.
#
# Usage: scripts/sync_roadmap.sh [--check]
#   --check  : verify the two files match; exit non-zero if they don't.
#              Use in CI to prevent drift.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${ROOT_DIR}/ROADMAP.md"
DST="${ROOT_DIR}/docs/roadmap.md"

HEADER=$'<!--\n  This file is auto-generated from /ROADMAP.md by scripts/sync_roadmap.sh.\n  GitHub readers see ROADMAP.md; mkdocs site renders this page.\n  Do not edit this file directly — edit ROADMAP.md and re-run the sync.\n-->\n\n'

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  printf '%s' "$HEADER" > "$TMP"
  cat "$SRC" >> "$TMP"
  if ! diff -q "$DST" "$TMP" >/dev/null; then
    echo "ERROR: docs/roadmap.md is out of sync with ROADMAP.md."
    echo "Run: scripts/sync_roadmap.sh"
    diff -u "$DST" "$TMP" | head -50
    exit 1
  fi
  echo "OK: docs/roadmap.md matches ROADMAP.md"
  exit 0
fi

printf '%s' "$HEADER" > "$DST"
cat "$SRC" >> "$DST"
echo "Synced ROADMAP.md → docs/roadmap.md"
